# Generated by Django 6.0.4 on 2026-05-05 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(help_text="Unique identifier e.g. 'dark-mode', 'new-checkout'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Global kill switch. False = off for everyone.')),
                ('rollout_percentage', models.PositiveSmallIntegerField(default=100, help_text='0–100. What % of users see this flag when active.')),
            ],
            options={
                'db_table': 'feature_flags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(help_text='ID from your system: UUID, user_123, hashed email, etc.', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'user_identifiers',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('feature_flag', models.OneToOneField(help_text='Each flag can have at most one experiment.', on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to='feature_flags.featureflag')),
            ],
            options={
                'db_table': 'experiments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'control', 'treatment', 'variant-b'", max_length=100)),
                ('weight', models.PositiveSmallIntegerField(default=50, help_text='Relative weight for assignment. control=50, treatment=50 → 50/50 split.')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='feature_flags.experiment')),
            ],
            options={
                'db_table': 'variants',
                'unique_together': {('experiment', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='feature_flags.experiment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='feature_flags.useridentifier')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='feature_flags.variant')),
            ],
            options={
                'db_table': 'assignments',
                'unique_together': {('user', 'experiment')},
            },
        ),
    ]
