# Generated by Django 6.0.4 on 2026-05-05 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0002_alter_experiment_feature_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='rollout_percentage',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0, message='Rollout percentage cannot be negative.'), django.core.validators.MaxValueValidator(100, message='Rollout percentage cannot exceed 100.')]),
        ),
        migrations.AlterField(
            model_name='useridentifier',
            name='external_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='weight',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1, message='Weight must be at least 1.')]),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['user', 'experiment'], name='idx_assignment_user_exp'),
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['status'], name='idx_experiment_status'),
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['feature_flag'], name='idx_experiment_flag'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['name'], name='idx_flag_name'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['is_active'], name='idx_flag_active'),
        ),
        migrations.AddIndex(
            model_name='metricevent',
            index=models.Index(fields=['experiment', 'event_type'], name='idx_event_exp_type'),
        ),
        migrations.AddIndex(
            model_name='metricevent',
            index=models.Index(fields=['variant', 'event_type'], name='idx_event_variant_type'),
        ),
        migrations.AddIndex(
            model_name='useridentifier',
            index=models.Index(fields=['external_id'], name='idx_user_external_id'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['experiment'], name='idx_variant_experiment'),
        ),
    ]
